# scripts/popular_100_produtos.py
import os
import sys
import django

# ⭐ AJUSTA O CAMINHO PARA A RAIZ DO PROJETO
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(script_dir))
sys.path.insert(0, project_root)

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'my_project_ia_rag_aws.settings')
django.setup()

from meu_app_rag.models import Produto

# 🎯 100 PRODUTOS DE TESTE - CATÁLOGO COMPLETO
produtos_teste = [
    # ========================================
    # ROUPAS MASCULINAS (15 produtos)
    # ========================================
    {
        "nome": "Camiseta Básica Branca",
        "categoria": "Roupas",
        "subcategoria": "Camisetas",
        "preco": 39.90,
        "marca": "BasicWear",
        "cor": "Branco",
        "tamanho": "M",
        "material": "100% algodão",
        "estoque": 150,
        "descricao": "Camiseta básica branca de algodão, perfeita para o dia a dia",
        "especificacoes": "Gola redonda, modelagem regular, malha de alta qualidade",
        "avaliacao": 4.3,
        "num_avaliacoes": 567,
        "peso": 0.2,
        "dimensoes": "30x25x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500"
    },
    {
        "nome": "Camiseta Preta Básica",
        "categoria": "Roupas",
        "subcategoria": "Camisetas",
        "preco": 39.90,
        "marca": "BasicWear",
        "cor": "Preto",
        "tamanho": "M",
        "material": "100% algodão",
        "estoque": 180,
        "descricao": "Camiseta básica preta essencial para qualquer guarda-roupa",
        "especificacoes": "Gola redonda, modelagem regular, malha pente",
        "avaliacao": 4.4,
        "num_avaliacoes": 623,
        "peso": 0.2,
        "dimensoes": "30x25x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500"
    },
    {
        "nome": "Camiseta Polo Azul Marinho",
        "categoria": "Roupas",
        "subcategoria": "Camisetas",
        "preco": 89.90,
        "marca": "PoloStyle",
        "cor": "Azul Marinho",
        "tamanho": "M",
        "material": "Piquet de algodão",
        "estoque": 95,
        "descricao": "Camisa polo clássica para ocasiões casuais elegantes",
        "especificacoes": "Gola com botões, bordado no peito, lavável",
        "avaliacao": 4.6,
        "num_avaliacoes": 412,
        "peso": 0.3,
        "dimensoes": "32x26x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=500"
    },
    {
        "nome": "Calça Jeans Skinny Masculina",
        "categoria": "Roupas",
        "subcategoria": "Calças",
        "preco": 149.90,
        "marca": "DenimPro",
        "cor": "Azul Escuro",
        "tamanho": "42",
        "material": "98% algodão, 2% elastano",
        "estoque": 55,
        "descricao": "Calça jeans skinny masculina com elastano para maior conforto",
        "especificacoes": "5 bolsos, stretch, lavagem escura",
        "avaliacao": 4.5,
        "num_avaliacoes": 523,
        "peso": 0.6,
        "dimensoes": "35x25x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500"
    },
    {
        "nome": "Calça Jeans Reta Clássica",
        "categoria": "Roupas",
        "subcategoria": "Calças",
        "preco": 129.90,
        "preco_promocional": 99.90,
        "marca": "DenimPro",
        "cor": "Azul Médio",
        "tamanho": "42",
        "material": "100% algodão",
        "estoque": 78,
        "descricao": "Calça jeans reta tradicional, confortável e durável",
        "especificacoes": "5 bolsos, lavagem média, modelagem reta",
        "avaliacao": 4.4,
        "num_avaliacoes": 389,
        "peso": 0.65,
        "dimensoes": "35x26x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1475178626620-a4d074967452?w=500"
    },
    {
        "nome": "Bermuda Sarja Bege",
        "categoria": "Roupas",
        "subcategoria": "Bermudas",
        "preco": 79.90,
        "marca": "CasualFit",
        "cor": "Bege",
        "tamanho": "42",
        "material": "Sarja de algodão",
        "estoque": 120,
        "descricao": "Bermuda sarja casual para o verão",
        "especificacoes": "4 bolsos, cós com passantes, acabamento premium",
        "avaliacao": 4.2,
        "num_avaliacoes": 267,
        "peso": 0.4,
        "dimensoes": "30x20x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500"
    },
    {
        "nome": "Moletom Canguru Unissex",
        "categoria": "Roupas",
        "subcategoria": "Moletons",
        "preco": 119.90,
        "marca": "ComfortWear",
        "cor": "Cinza Mescla",
        "tamanho": "M",
        "material": "Algodão e poliéster",
        "estoque": 76,
        "descricao": "Moletom canguru clássico com capuz e bolso frontal",
        "especificacoes": "Capuz com cordão, bolso canguru, felpa interna",
        "avaliacao": 4.7,
        "num_avaliacoes": 845,
        "peso": 0.6,
        "dimensoes": "35x30x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500"
    },
    {
        "nome": "Jaqueta Jeans Masculina",
        "categoria": "Roupas",
        "subcategoria": "Jaquetas",
        "preco": 189.90,
        "preco_promocional": 149.90,
        "marca": "DenimPro",
        "cor": "Azul",
        "tamanho": "M",
        "material": "Jeans 100% algodão",
        "estoque": 42,
        "descricao": "Jaqueta jeans clássica, versátil e atemporal",
        "especificacoes": "Botões metálicos, 2 bolsos frontais, gola tradicional",
        "avaliacao": 4.6,
        "num_avaliacoes": 534,
        "peso": 0.8,
        "dimensoes": "40x35x6cm",
        "imagem_url": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500"
    },
    {
        "nome": "Camisa Social Branca Slim",
        "categoria": "Roupas",
        "subcategoria": "Camisas",
        "preco": 129.90,
        "marca": "ExecutiveWear",
        "cor": "Branco",
        "tamanho": "M",
        "material": "Tricoline",
        "estoque": 88,
        "descricao": "Camisa social slim fit para ocasiões formais",
        "especificacoes": "Manga longa, corte slim, não amassa",
        "avaliacao": 4.5,
        "num_avaliacoes": 456,
        "peso": 0.35,
        "dimensoes": "35x28x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=500"
    },
    {
        "nome": "Regata Fitness Dry-Fit",
        "categoria": "Roupas",
        "subcategoria": "Roupas Esportivas",
        "preco": 49.90,
        "marca": "SportActive",
        "cor": "Preto",
        "tamanho": "M",
        "material": "Poliéster dry-fit",
        "estoque": 145,
        "descricao": "Regata esportiva com tecnologia de secagem rápida",
        "especificacoes": "Respirável, anti-odor, proteção UV",
        "avaliacao": 4.4,
        "num_avaliacoes": 389,
        "peso": 0.15,
        "dimensoes": "28x22x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1558449028-b53a39d100fc?w=500"
    },
    {
        "nome": "Shorts Esportivo Academia",
        "categoria": "Roupas",
        "subcategoria": "Roupas Esportivas",
        "preco": 69.90,
        "marca": "SportActive",
        "cor": "Preto/Cinza",
        "tamanho": "M",
        "material": "Poliamida e elastano",
        "estoque": 110,
        "descricao": "Shorts esportivo leve e confortável para treinos",
        "especificacoes": "Bolso com zíper, elástico na cintura, respirável",
        "avaliacao": 4.3,
        "num_avaliacoes": 298,
        "peso": 0.2,
        "dimensoes": "28x20x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1591195120907-7d72ebf3f754?w=500"
    },
    {
        "nome": "Cueca Boxer Kit 3 Unidades",
        "categoria": "Roupas",
        "subcategoria": "Underwear",
        "preco": 59.90,
        "marca": "ComfortFit",
        "cor": "Cores Variadas",
        "tamanho": "M",
        "material": "Algodão e elastano",
        "estoque": 200,
        "descricao": "Kit com 3 cuecas boxer de alta qualidade",
        "especificacoes": "Elástico embutido, costura reforçada, macio",
        "avaliacao": 4.6,
        "num_avaliacoes": 1245,
        "peso": 0.2,
        "dimensoes": "25x20x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500"
    },
    {
        "nome": "Pijama Masculino Conforto",
        "categoria": "Roupas",
        "subcategoria": "Sleepwear",
        "preco": 89.90,
        "marca": "SleepWell",
        "cor": "Azul Marinho",
        "tamanho": "M",
        "material": "Malha 100% algodão",
        "estoque": 67,
        "descricao": "Pijama confortável para noites tranquilas",
        "especificacoes": "Calça com elástico, camiseta lisa, macio",
        "avaliacao": 4.5,
        "num_avaliacoes": 234,
        "peso": 0.4,
        "dimensoes": "32x25x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500"
    },
    {
        "nome": "Suéter Tricot Cinza",
        "categoria": "Roupas",
        "subcategoria": "Suéteres",
        "preco": 159.90,
        "marca": "WinterStyle",
        "cor": "Cinza",
        "tamanho": "M",
        "material": "Lã e acrílico",
        "estoque": 54,
        "descricao": "Suéter de tricot elegante para dias frios",
        "especificacoes": "Gola V, manga longa, acabamento premium",
        "avaliacao": 4.7,
        "num_avaliacoes": 189,
        "peso": 0.5,
        "dimensoes": "35x30x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1620799139834-6b8f844fbe29?w=500"
    },
    {
        "nome": "Colete Puffer Preto",
        "categoria": "Roupas",
        "subcategoria": "Coletes",
        "preco": 179.90,
        "marca": "WinterStyle",
        "cor": "Preto",
        "tamanho": "M",
        "material": "Nylon com enchimento sintético",
        "estoque": 38,
        "descricao": "Colete estilo puffer para o inverno",
        "especificacoes": "2 bolsos com zíper, capuz removível, leve",
        "avaliacao": 4.5,
        "num_avaliacoes": 276,
        "peso": 0.6,
        "dimensoes": "40x32x6cm",
        "imagem_url": "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=500"
    },

    # ========================================
    # ROUPAS FEMININAS (15 produtos)
    # ========================================
    {
        "nome": "Vestido Midi Floral",
        "categoria": "Roupas",
        "subcategoria": "Vestidos",
        "preco": 149.90,
        "preco_promocional": 119.90,
        "marca": "FlowerStyle",
        "cor": "Floral",
        "tamanho": "M",
        "material": "Viscose",
        "estoque": 34,
        "descricao": "Vestido midi com estampa floral romântica para ocasiões especiais",
        "especificacoes": "Alças finas, cintura marcada, forro interno",
        "avaliacao": 4.8,
        "num_avaliacoes": 678,
        "peso": 0.35,
        "dimensoes": "40x30x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500"
    },
    {
        "nome": "Blusa Cropped Branca",
        "categoria": "Roupas",
        "subcategoria": "Blusas",
        "preco": 59.90,
        "marca": "TrendyFashion",
        "cor": "Branco",
        "tamanho": "M",
        "material": "Malha canelada",
        "estoque": 125,
        "descricao": "Blusa cropped moderna e versátil",
        "especificacoes": "Manga curta, comprimento na cintura, decote redondo",
        "avaliacao": 4.4,
        "num_avaliacoes": 445,
        "peso": 0.15,
        "dimensoes": "25x20x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500"
    },
    {
        "nome": "Calça Legging Fitness",
        "categoria": "Roupas",
        "subcategoria": "Roupas Esportivas",
        "preco": 89.90,
        "marca": "FitActive",
        "cor": "Preto",
        "tamanho": "M",
        "material": "Poliamida e elastano",
        "estoque": 156,
        "descricao": "Legging de alta compressão para treinos",
        "especificacoes": "Cintura alta, bolso, modeladora, anti-celulite",
        "avaliacao": 4.7,
        "num_avaliacoes": 1023,
        "peso": 0.25,
        "dimensoes": "30x22x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500"
    },
    {
        "nome": "Saia Jeans Midi",
        "categoria": "Roupas",
        "subcategoria": "Saias",
        "preco": 119.90,
        "marca": "DenimChic",
        "cor": "Azul Médio",
        "tamanho": "M",
        "material": "Jeans stretch",
        "estoque": 68,
        "descricao": "Saia jeans midi com botões frontais",
        "especificacoes": "Fenda frontal, botões decorativos, bolsos",
        "avaliacao": 4.5,
        "num_avaliacoes": 342,
        "peso": 0.4,
        "dimensoes": "32x25x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500"
    },
    {
        "nome": "Top Fitness Rosa",
        "categoria": "Roupas",
        "subcategoria": "Roupas Esportivas",
        "preco": 69.90,
        "marca": "FitActive",
        "cor": "Rosa",
        "tamanho": "M",
        "material": "Poliamida dry-fit",
        "estoque": 145,
        "descricao": "Top esportivo com bojo removível",
        "especificacoes": "Alças ajustáveis, respirável, suporte médio",
        "avaliacao": 4.6,
        "num_avaliacoes": 567,
        "peso": 0.12,
        "dimensoes": "25x20x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1598522325074-042db73aa4e6?w=500"
    },
    {
        "nome": "Jaqueta Bomber Feminina",
        "categoria": "Roupas",
        "subcategoria": "Jaquetas",
        "preco": 199.90,
        "preco_promocional": 159.90,
        "marca": "UrbanStyle",
        "cor": "Verde Militar",
        "tamanho": "M",
        "material": "Nylon",
        "estoque": 47,
        "descricao": "Jaqueta bomber estilo militar",
        "especificacoes": "Zíper frontal, 2 bolsos, punhos elásticos",
        "avaliacao": 4.7,
        "num_avaliacoes": 389,
        "peso": 0.5,
        "dimensoes": "38x32x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500"
    },
    {
        "nome": "Conjunto Pijama Cetim",
        "categoria": "Roupas",
        "subcategoria": "Sleepwear",
        "preco": 129.90,
        "marca": "SilkDream",
        "cor": "Rosa Claro",
        "tamanho": "M",
        "material": "Cetim",
        "estoque": 55,
        "descricao": "Conjunto de pijama luxuoso em cetim",
        "especificacoes": "Blusa com botões, short com elástico, delicado",
        "avaliacao": 4.8,
        "num_avaliacoes": 423,
        "peso": 0.3,
        "dimensoes": "30x25x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1609623997987-cea5ad2f56e7?w=500"
    },
    {
        "nome": "Macaquinho Jeans",
        "categoria": "Roupas",
        "subcategoria": "Macacões",
        "preco": 169.90,
        "marca": "DenimChic",
        "cor": "Azul Claro",
        "tamanho": "M",
        "material": "Jeans",
        "estoque": 42,
        "descricao": "Macaquinho jeans casual e confortável",
        "especificacoes": "Alças ajustáveis, bolsos laterais, cinto",
        "avaliacao": 4.6,
        "num_avaliacoes": 267,
        "peso": 0.45,
        "dimensoes": "35x28x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1564328538539-28ff46c93148?w=500"
    },
    {
        "nome": "Cardigan Longo Bege",
        "categoria": "Roupas",
        "subcategoria": "Cardigans",
        "preco": 139.90,
        "marca": "CozyKnit",
        "cor": "Bege",
        "tamanho": "M",
        "material": "Tricot",
        "estoque": 58,
        "descricao": "Cardigan longo elegante para o frio",
        "especificacoes": "Comprimento até o joelho, bolsos, botões",
        "avaliacao": 4.7,
        "num_avaliacoes": 312,
        "peso": 0.6,
        "dimensoes": "40x32x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=500"
    },
    {
        "nome": "Blusa Ombro a Ombro",
        "categoria": "Roupas",
        "subcategoria": "Blusas",
        "preco": 79.90,
        "marca": "TrendyFashion",
        "cor": "Branco",
        "tamanho": "M",
        "material": "Linho",
        "estoque": 92,
        "descricao": "Blusa ciganinha romântica",
        "especificacoes": "Elástico no ombro, manga 3/4, fluida",
        "avaliacao": 4.5,
        "num_avaliacoes": 456,
        "peso": 0.2,
        "dimensoes": "30x25x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1566206091558-7f218e1a799a?w=500"
    },
    {
        "nome": "Short Jeans Destroyed",
        "categoria": "Roupas",
        "subcategoria": "Shorts",
        "preco": 89.90,
        "preco_promocional": 69.90,
        "marca": "DenimChic",
        "cor": "Azul Médio",
        "tamanho": "M",
        "material": "Jeans",
        "estoque": 105,
        "descricao": "Short jeans com efeito destroyed",
        "especificacoes": "Barra desfiada, rasgos, 5 bolsos",
        "avaliacao": 4.4,
        "num_avaliacoes": 389,
        "peso": 0.3,
        "dimensoes": "28x22x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500"
    },
    {
        "nome": "Vestido Longo Festa",
        "categoria": "Roupas",
        "subcategoria": "Vestidos",
        "preco": 299.90,
        "marca": "ElegantDress",
        "cor": "Vinho",
        "tamanho": "M",
        "material": "Cetim",
        "estoque": 28,
        "descricao": "Vestido longo sofisticado para festas",
        "especificacoes": "Fenda lateral, costas abertas, forro",
        "avaliacao": 4.9,
        "num_avaliacoes": 234,
        "peso": 0.5,
        "dimensoes": "42x32x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500"
    },
    {
        "nome": "Conjunto Moletom Feminino",
        "categoria": "Roupas",
        "subcategoria": "Conjuntos",
        "preco": 179.90,
        "marca": "ComfortWear",
        "cor": "Rosa",
        "tamanho": "M",
        "material": "Moletom flanelado",
        "estoque": 72,
        "descricao": "Conjunto de moletom confortável",
        "especificacoes": "Blusa cropped com capuz, calça jogger",
        "avaliacao": 4.6,
        "num_avaliacoes": 523,
        "peso": 0.8,
        "dimensoes": "38x30x6cm",
        "imagem_url": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500"
    },
    {
        "nome": "Regata Nadador Fitness",
        "categoria": "Roupas",
        "subcategoria": "Roupas Esportivas",
        "preco": 54.90,
        "marca": "FitActive",
        "cor": "Cinza Mescla",
        "tamanho": "M",
        "material": "Poliamida",
        "estoque": 167,
        "descricao": "Regata nadador para treinos intensos",
        "especificacoes": "Respirável, modeladora, secagem rápida",
        "avaliacao": 4.5,
        "num_avaliacoes": 612,
        "peso": 0.12,
        "dimensoes": "26x20x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1598522325074-042db73aa4e6?w=500"
    },
    {
        "nome": "Kimono Floral Longo",
        "categoria": "Roupas",
        "subcategoria": "Kimonos",
        "preco": 129.90,
        "marca": "BohoStyle",
        "cor": "Estampa Floral",
        "tamanho": "Único",
        "material": "Viscose",
        "estoque": 45,
        "descricao": "Kimono longo estilo boho",
        "especificacoes": "Manga 3/4, comprimento longo, fluido",
        "avaliacao": 4.7,
        "num_avaliacoes": 298,
        "peso": 0.4,
        "dimensoes": "40x32x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1595341888006-0b8806f5c30a?w=500"
    },

    # ========================================
    # CALÇADOS (15 produtos)
    # ========================================
    {
        "nome": "Tênis Corrida Pro Run",
        "categoria": "Calçados",
        "subcategoria": "Tênis",
        "preco": 199.90,
        "preco_promocional": 149.90,
        "marca": "SportPro",
        "cor": "Branco/Azul",
        "tamanho": "42",
        "material": "Tecido respirável mesh",
        "estoque": 30,
        "descricao": "Tênis leve para corrida com amortecimento de alta performance",
        "especificacoes": "Solado EVA, palmilha anatômica, respirável",
        "avaliacao": 4.8,
        "num_avaliacoes": 250,
        "peso": 0.35,
        "dimensoes": "30x12x10cm",
        "imagem_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500"
    },
    {
        "nome": "Tênis Casual Branco",
        "categoria": "Calçados",
        "subcategoria": "Tênis",
        "preco": 179.90,
        "marca": "UrbanWalk",
        "cor": "Branco",
        "tamanho": "40",
        "material": "Couro sintético",
        "estoque": 85,
        "descricao": "Tênis branco clássico para o dia a dia",
        "especificacoes": "Palmilha acolchoada, solado de borracha, durável",
        "avaliacao": 4.6,
        "num_avaliacoes": 678,
        "peso": 0.4,
        "dimensoes": "30x12x10cm",
        "imagem_url": "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500"
    },
    {
        "nome": "Tênis Chunky Feminino",
        "categoria": "Calçados",
        "subcategoria": "Tênis",
        "preco": 219.90,
        "preco_promocional": 179.90,
        "marca": "TrendyShoes",
        "cor": "Branco/Rosa",
        "tamanho": "37",
        "material": "Sintético",
        "estoque": 52,
        "descricao": "Tênis chunky moderno e confortável",
        "especificacoes": "Solado alto, palmilha macia, design moderno",
        "avaliacao": 4.7,
        "num_avaliacoes": 423,
        "peso": 0.6,
        "dimensoes": "28x11x12cm",
        "imagem_url": "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=500"
    },
    {
        "nome": "Sandália Rasteira Confort",
        "categoria": "Calçados",
        "subcategoria": "Sandálias",
        "preco": 89.90,
        "marca": "ComfortFeet",
        "cor": "Caramelo",
        "tamanho": "37",
        "material": "Couro legítimo",
        "estoque": 95,
        "descricao": "Sandália rasteira confortável para o verão",
        "especificacoes": "Palmilha anatômica, tiras ajustáveis, solado antiderrapante",
        "avaliacao": 4.5,
        "num_avaliacoes": 534,
        "peso": 0.25,
        "dimensoes": "26x10x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500"
    },
    {
        "nome": "Chinelo Slide Preto",
        "categoria": "Calçados",
        "subcategoria": "Chinelos",
        "preco": 69.90,
        "marca": "SlideStyle",
        "cor": "Preto",
        "tamanho": "42",
        "material": "EVA",
        "estoque": 180,
        "descricao": "Chinelo slide confortável e prático",
        "especificacoes": "Palmilha macia, solado antiderrapante, leve",
        "avaliacao": 4.4,
        "num_avaliacoes": 892,
        "peso": 0.2,
        "dimensoes": "28x10x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500"
    },
    {
        "nome": "Bota Coturno Feminina",
        "categoria": "Calçados",
        "subcategoria": "Botas",
        "preco": 249.90,
        "marca": "UrbanStyle",
        "cor": "Preto",
        "tamanho": "37",
        "material": "Couro sintético",
        "estoque": 48,
        "descricao": "Bota coturno estilo rock urbano",
        "especificacoes": "Cadarço, solado tratorado, cano médio",
        "avaliacao": 4.7,
        "num_avaliacoes": 367,
        "peso": 0.9,
        "dimensoes": "30x12x15cm",
        "imagem_url": "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=500"
    },
    {
        "nome": "Sapato Social Masculino",
        "categoria": "Calçados",
        "subcategoria": "Sapatos Sociais",
        "preco": 189.90,
        "marca": "ExecutiveShoes",
        "cor": "Preto",
        "tamanho": "42",
        "material": "Couro sintético",
        "estoque": 67,
        "descricao": "Sapato social clássico para ocasiões formais",
        "especificacoes": "Cadarço, bico fino, solado de borracha",
        "avaliacao": 4.5,
        "num_avaliacoes": 445,
        "peso": 0.7,
        "dimensoes": "30x11x10cm",
        "imagem_url": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500"
    },
    {
        "nome": "Sapatilha Bico Fino",
        "categoria": "Calçados",
        "subcategoria": "Sapatilhas",
        "preco": 79.90,
        "marca": "ChicFlat",
        "cor": "Nude",
        "tamanho": "37",
        "material": "Sintético",
        "estoque": 115,
        "descricao": "Sapatilha elegante e confortável",
        "especificacoes": "Bico fino, palmilha acolchoada, versátil",
        "avaliacao": 4.3,
        "num_avaliacoes": 612,
        "peso": 0.3,
        "dimensoes": "26x9x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500"
    },
    {
        "nome": "Tênis Slip On Masculino",
        "categoria": "Calçados",
        "subcategoria": "Tênis",
        "preco": 139.90,
        "marca": "CasualFit",
        "cor": "Cinza",
        "tamanho": "42",
        "material": "Lona",
        "estoque": 78,
        "descricao": "Tênis slip on prático e confortável",
        "especificacoes": "Sem cadarço, elástico lateral, leve",
        "avaliacao": 4.4,
        "num_avaliacoes": 389,
        "peso": 0.35,
        "dimensoes": "29x11x9cm",
        "imagem_url": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500"
    },
    {
        "nome": "Scarpin Salto Alto",
        "categoria": "Calçados",
        "subcategoria": "Scarpins",
        "preco": 159.90,
        "preco_promocional": 129.90,
        "marca": "ElegantHeels",
        "cor": "Preto",
        "tamanho": "37",
        "material": "Verniz",
        "estoque": 42,
        "descricao": "Scarpin clássico para ocasiões elegantes",
        "especificacoes": "Salto 10cm, bico fino, palmilha macia",
        "avaliacao": 4.6,
        "num_avaliacoes": 289,
        "peso": 0.5,
        "dimensoes": "26x9x12cm",
        "imagem_url": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500"
    },
    {
        "nome": "Tênis Plataforma Branco",
        "categoria": "Calçados",
        "subcategoria": "Tênis",
        "preco": 189.90,
        "marca": "TrendyShoes",
        "cor": "Branco",
        "tamanho": "37",
        "material": "Couro sintético",
        "estoque": 58,
        "descricao": "Tênis com plataforma moderno",
        "especificacoes": "Solado alto 5cm, cadarço, confortável",
        "avaliacao": 4.7,
        "num_avaliacoes": 456,
        "peso": 0.6,
        "dimensoes": "28x10x11cm",
        "imagem_url": "https://images.unsplash.com/photo-1562183241-b937e95585b6?w=500"
    },
    {
        "nome": "Sandália Salto Bloco",
        "categoria": "Calçados",
        "subcategoria": "Sandálias",
        "preco": 129.90,
        "marca": "ComfortHeels",
        "cor": "Bege",
        "tamanho": "37",
        "material": "Suede",
        "estoque": 72,
        "descricao": "Sandália com salto bloco confortável",
        "especificacoes": "Salto 7cm, tiras cruzadas, fivela ajustável",
        "avaliacao": 4.5,
        "num_avaliacoes": 378,
        "peso": 0.4,
        "dimensoes": "26x9x10cm",
        "imagem_url": "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=500"
    },
    {
        "nome": "Alpargata Espadrille",
        "categoria": "Calçados",
        "subcategoria": "Alpargatas",
        "preco": 99.90,
        "marca": "SummerStyle",
        "cor": "Listrado",
        "tamanho": "39",
        "material": "Lona e juta",
        "estoque": 89,
        "descricao": "Alpargata estilo espadrille para o verão",
        "especificacoes": "Solado de juta, confortável, respirável",
        "avaliacao": 4.4,
        "num_avaliacoes": 267,
        "peso": 0.3,
        "dimensoes": "27x10x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1619784299539-c3c3ab2f1f29?w=500"
    },
    {
        "nome": "Mocassim Masculino Couro",
        "categoria": "Calçados",
        "subcategoria": "Mocassins",
        "preco": 169.90,
        "marca": "ClassicShoes",
        "cor": "Marrom",
        "tamanho": "42",
        "material": "Couro legítimo",
        "estoque": 54,
        "descricao": "Mocassim elegante de couro",
        "especificacoes": "Sem cadarço, costura reforçada, palmilha confort",
        "avaliacao": 4.6,
        "num_avaliacoes": 312,
        "peso": 0.6,
        "dimensoes": "30x11x9cm",
        "imagem_url": "https://images.unsplash.com/photo-1478186014654-86440e11c6c9?w=500"
    },
    {
        "nome": "Papete Confort Masculina",
        "categoria": "Calçados",
        "subcategoria": "Papetes",
        "preco": 89.90,
        "marca": "OutdoorFeet",
        "cor": "Preto",
        "tamanho": "42",
        "material": "Sintético",
        "estoque": 125,
        "descricao": "Papete confortável para atividades ao ar livre",
        "especificacoes": "Tiras ajustáveis, solado antiderrapante, leve",
        "avaliacao": 4.3,
        "num_avaliacoes": 445,
        "peso": 0.4,
        "dimensoes": "29x11x7cm",
        "imagem_url": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=500"
    },

    # ========================================
    # ELETRÔNICOS (10 produtos)
    # ========================================
    {
        "nome": "Smartwatch Fitness Pro",
        "categoria": "Eletrônicos",
        "subcategoria": "Wearables",
        "preco": 599.90,
        "preco_promocional": 449.90,
        "marca": "TechFit",
        "cor": "Preto",
        "material": "Silicone e alumínio",
        "estoque": 42,
        "descricao": "Smartwatch com monitor cardíaco, GPS e bateria de 7 dias",
        "especificacoes": "Tela AMOLED 1.4', Bluetooth 5.0, IP68, Android/iOS",
        "avaliacao": 4.8,
        "num_avaliacoes": 892,
        "peso": 0.045,
        "dimensoes": "4.5x4.5x1.2cm",
        "imagem_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500"
    },
    {
        "nome": "Fone Bluetooth Premium",
        "categoria": "Eletrônicos",
        "subcategoria": "Áudio",
        "preco": 399.90,
        "marca": "SoundMax",
        "cor": "Branco",
        "material": "Plástico ABS",
        "estoque": 53,
        "descricao": "Fone over-ear com cancelamento ativo de ruído e 30h de bateria",
        "especificacoes": "ANC, aptX HD, Bluetooth 5.2, dobrável, case incluso",
        "avaliacao": 4.8,
        "num_avaliacoes": 712,
        "peso": 0.25,
        "dimensoes": "20x18x8cm",
        "imagem_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500"
    },
    {
        "nome": "Fone In-Ear Esportivo",
        "categoria": "Eletrônicos",
        "subcategoria": "Áudio",
        "preco": 149.90,
        "marca": "SportSound",
        "cor": "Preto",
        "material": "Silicone",
        "estoque": 145,
        "descricao": "Fone in-ear resistente à água para esportes",
        "especificacoes": "IPX7, gancho de orelha, 8h bateria, Bluetooth 5.0",
        "avaliacao": 4.5,
        "num_avaliacoes": 523,
        "peso": 0.02,
        "dimensoes": "5x4x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500"
    },
    {
        "nome": "Caixa de Som Portátil",
        "categoria": "Eletrônicos",
        "subcategoria": "Áudio",
        "preco": 279.90,
        "preco_promocional": 219.90,
        "marca": "SoundWave",
        "cor": "Azul",
        "material": "Plástico resistente",
        "estoque": 68,
        "descricao": "Caixa de som Bluetooth portátil à prova d'água",
        "especificacoes": "20W, IPX7, 12h bateria, entrada auxiliar",
        "avaliacao": 4.7,
        "num_avaliacoes": 445,
        "peso": 0.6,
        "dimensoes": "18x7x7cm",
        "imagem_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500"
    },
    {
        "nome": "Power Bank 20000mAh",
        "categoria": "Eletrônicos",
        "subcategoria": "Acessórios",
        "preco": 129.90,
        "marca": "ChargeMax",
        "cor": "Preto",
        "material": "Alumínio",
        "estoque": 95,
        "descricao": "Carregador portátil de alta capacidade",
        "especificacoes": "2 portas USB, entrada Type-C, LED indicador",
        "avaliacao": 4.6,
        "num_avaliacoes": 678,
        "peso": 0.4,
        "dimensoes": "15x7x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1609592842196-be7f867f6a74?w=500"
    },
    {
        "nome": "Webcam Full HD 1080p",
        "categoria": "Eletrônicos",
        "subcategoria": "Periféricos",
        "preco": 199.90,
        "marca": "StreamPro",
        "cor": "Preto",
        "material": "Plástico",
        "estoque": 78,
        "descricao": "Webcam para reuniões e streaming",
        "especificacoes": "1080p 30fps, microfone embutido, foco automático",
        "avaliacao": 4.5,
        "num_avaliacoes": 389,
        "peso": 0.15,
        "dimensoes": "8x8x6cm",
        "imagem_url": "https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?w=500"
    },
    {
        "nome": "Mouse Gamer RGB",
        "categoria": "Eletrônicos",
        "subcategoria": "Periféricos",
        "preco": 159.90,
        "preco_promocional": 119.90,
        "marca": "GameTech",
        "cor": "Preto",
        "material": "Plástico ABS",
        "estoque": 112,
        "descricao": "Mouse gamer com iluminação RGB e 7 botões",
        "especificacoes": "12000 DPI, 7 botões programáveis, cabo trançado",
        "avaliacao": 4.7,
        "num_avaliacoes": 567,
        "peso": 0.12,
        "dimensoes": "12x7x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500"
    },
    {
        "nome": "Teclado Mecânico RGB",
        "categoria": "Eletrônicos",
        "subcategoria": "Periféricos",
        "preco": 399.90,
        "marca": "GameTech",
        "cor": "Preto",
        "material": "Alumínio e plástico",
        "estoque": 54,
        "descricao": "Teclado mecânico para gamers e digitadores",
        "especificacoes": "Switch blue, RGB personalizável, anti-ghosting",
        "avaliacao": 4.8,
        "num_avaliacoes": 445,
        "peso": 0.9,
        "dimensoes": "44x14x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1595225476474-87563907a212?w=500"
    },
    {
        "nome": "Ring Light 10 Polegadas",
        "categoria": "Eletrônicos",
        "subcategoria": "Iluminação",
        "preco": 149.90,
        "marca": "LightPro",
        "cor": "Branco",
        "material": "Plástico",
        "estoque": 87,
        "descricao": "Ring light para fotos e vídeos profissionais",
        "especificacoes": "10', 3 tons de luz, tripé incluso, suporte celular",
        "avaliacao": 4.6,
        "num_avaliacoes": 734,
        "peso": 0.6,
        "dimensoes": "28x28x10cm",
        "imagem_url": "https://images.unsplash.com/photo-1608988373359-c2fd3a4a0400?w=500"
    },
    {
        "nome": "Tablet 10 Polegadas",
        "categoria": "Eletrônicos",
        "subcategoria": "Tablets",
        "preco": 899.90,
        "preco_promocional": 799.90,
        "marca": "TabletPro",
        "cor": "Prata",
        "material": "Alumínio",
        "estoque": 35,
        "descricao": "Tablet de alta performance para trabalho e entretenimento",
        "especificacoes": "10.1', 4GB RAM, 64GB, Android 12, Wi-Fi",
        "avaliacao": 4.7,
        "num_avaliacoes": 289,
        "peso": 0.5,
        "dimensoes": "24x17x0.8cm",
        "imagem_url": "https://images.unsplash.com/photo-1585790050230-5dd28404f29a?w=500"
    },

    # ========================================
    # ACESSÓRIOS (10 produtos)
    # ========================================
    {
        "nome": "Mochila Executiva Antifurto",
        "categoria": "Acessórios",
        "subcategoria": "Mochilas",
        "preco": 189.90,
        "marca": "SafeBag",
        "cor": "Cinza",
        "material": "Poliéster impermeável",
        "estoque": 67,
        "descricao": "Mochila com compartimento para notebook 15.6' e USB charging port",
        "especificacoes": "Zíperes ocultos, bolso RFID, alças ergonômicas, 25L",
        "avaliacao": 4.5,
        "num_avaliacoes": 324,
        "peso": 0.8,
        "dimensoes": "45x30x15cm",
        "imagem_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500"
    },
    {
        "nome": "Bolsa Tiracolo Feminina",
        "categoria": "Acessórios",
        "subcategoria": "Bolsas",
        "preco": 129.90,
        "preco_promocional": 99.90,
        "marca": "ChicBag",
        "cor": "Caramelo",
        "material": "Couro sintético",
        "estoque": 92,
        "descricao": "Bolsa tiracolo elegante e prática",
        "especificacoes": "Alça ajustável, 2 compartimentos, fecho magnético",
        "avaliacao": 4.6,
        "num_avaliacoes": 567,
        "peso": 0.5,
        "dimensoes": "25x18x8cm",
        "imagem_url": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500"
    },
    {
        "nome": "Carteira Masculina Couro",
        "categoria": "Acessórios",
        "subcategoria": "Carteiras",
        "preco": 89.90,
        "marca": "LeatherStyle",
        "cor": "Marrom",
        "material": "Couro legítimo",
        "estoque": 145,
        "descricao": "Carteira de couro com múltiplos compartimentos",
        "especificacoes": "6 porta-cartões, 2 porta-notas, porta-moedas",
        "avaliacao": 4.5,
        "num_avaliacoes": 678,
        "peso": 0.12,
        "dimensoes": "12x9x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=500"
    },
    {
        "nome": "Óculos de Sol Aviador",
        "categoria": "Acessórios",
        "subcategoria": "Óculos",
        "preco": 149.90,
        "marca": "SunStyle",
        "cor": "Dourado",
        "material": "Metal e acrílico",
        "estoque": 78,
        "descricao": "Óculos estilo aviador com proteção UV400",
        "especificacoes": "Lente polarizada, armação metal, case incluso",
        "avaliacao": 4.7,
        "num_avaliacoes": 445,
        "peso": 0.03,
        "dimensoes": "15x5x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500"
    },
    {
        "nome": "Relógio Analógico Clássico",
        "categoria": "Acessórios",
        "subcategoria": "Relógios",
        "preco": 279.90,
        "marca": "TimeStyle",
        "cor": "Prata",
        "material": "Aço inoxidável",
        "estoque": 54,
        "descricao": "Relógio analógico elegante e atemporal",
        "especificacoes": "Resistente à água 5ATM, vidro mineral, pulseira ajustável",
        "avaliacao": 4.6,
        "num_avaliacoes": 312,
        "peso": 0.15,
        "dimensoes": "4x4x1cm",
        "imagem_url": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=500"
    },
    {
        "nome": "Cinto Couro Masculino",
        "categoria": "Acessórios",
        "subcategoria": "Cintos",
        "preco": 79.90,
        "marca": "LeatherStyle",
        "cor": "Preto",
        "material": "Couro legítimo",
        "estoque": 156,
        "descricao": "Cinto de couro clássico para o dia a dia",
        "especificacoes": "Fivela metálica, ajustável, largura 4cm",
        "avaliacao": 4.4,
        "num_avaliacoes": 523,
        "peso": 0.25,
        "dimensoes": "110x4x0.4cm",
        "imagem_url": "https://images.unsplash.com/photo-1624222247344-550fb60583b8?w=500"
    },
    {
        "nome": "Lenço Seda Estampado",
        "categoria": "Acessórios",
        "subcategoria": "Lenços",
        "preco": 69.90,
        "marca": "SilkStyle",
        "cor": "Estampado",
        "material": "Seda",
        "estoque": 105,
        "descricao": "Lenço de seda versátil e elegante",
        "especificacoes": "90x90cm, estampa floral, multi-uso",
        "avaliacao": 4.5,
        "num_avaliacoes": 267,
        "peso": 0.05,
        "dimensoes": "25x20x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=500"
    },
    {
        "nome": "Boné Aba Reta Preto",
        "categoria": "Acessórios",
        "subcategoria": "Bonés",
        "preco": 59.90,
        "marca": "UrbanCap",
        "cor": "Preto",
        "material": "Algodão",
        "estoque": 178,
        "descricao": "Boné aba reta estilo urbano",
        "especificacoes": "Ajustável, bordado frontal, ventilação",
        "avaliacao": 4.3,
        "num_avaliacoes": 612,
        "peso": 0.1,
        "dimensoes": "20x15x10cm",
        "imagem_url": "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500"
    },
    {
        "nome": "Gravata Seda Azul Marinho",
        "categoria": "Acessórios",
        "subcategoria": "Gravatas",
        "preco": 89.90,
        "marca": "ExecutiveStyle",
        "cor": "Azul Marinho",
        "material": "Seda",
        "estoque": 125,
        "descricao": "Gravata de seda para ocasiões formais",
        "especificacoes": "8cm largura, 145cm comprimento, estampa lisa",
        "avaliacao": 4.5,
        "num_avaliacoes": 198,
        "peso": 0.08,
        "dimensoes": "30x10x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=500"
    },
    {
        "nome": "Mala de Viagem Grande",
        "categoria": "Acessórios",
        "subcategoria": "Malas",
        "preco": 399.90,
        "preco_promocional": 329.90,
        "marca": "TravelPro",
        "cor": "Preta",
        "material": "ABS rígido",
        "estoque": 28,
        "descricao": "Mala de viagem resistente com rodas 360°",
        "especificacoes": "80L, 4 rodas, cadeado TSA, alça telescópica",
        "avaliacao": 4.7,
        "num_avaliacoes": 289,
        "peso": 4.5,
        "dimensoes": "75x50x30cm",
        "imagem_url": "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=500"
    },

    # ========================================
    # BELEZA (10 produtos)
    # ========================================
    {
        "nome": "Perfume Masculino Intense",
        "categoria": "Beleza",
        "subcategoria": "Perfumes",
        "preco": 289.90,
        "marca": "FragrancePro",
        "cor": "N/A",
        "material": "Eau de Parfum",
        "estoque": 45,
        "descricao": "Perfume masculino sofisticado com notas amadeiradas e cítricas",
        "especificacoes": "100ml, concentração 15%, notas: bergamota, cedro e âmbar",
        "avaliacao": 4.9,
        "num_avaliacoes": 567,
        "peso": 0.3,
        "dimensoes": "12x6x6cm",
        "imagem_url": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=500"
    },
    {
        "nome": "Perfume Feminino Floral",
        "categoria": "Beleza",
        "subcategoria": "Perfumes",
        "preco": 259.90,
        "preco_promocional": 219.90,
        "marca": "FragrancePro",
        "cor": "N/A",
        "material": "Eau de Toilette",
        "estoque": 62,
        "descricao": "Perfume feminino com notas florais e frutadas",
        "especificacoes": "100ml, concentração 12%, notas: rosa, pêssego e jasmim",
        "avaliacao": 4.8,
        "num_avaliacoes": 734,
        "peso": 0.3,
        "dimensoes": "12x6x6cm",
        "imagem_url": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=500"
    },
    {
        "nome": "Kit Maquiagem Completo",
        "categoria": "Beleza",
        "subcategoria": "Maquiagem",
        "preco": 179.90,
        "marca": "BeautyPro",
        "cor": "Variado",
        "material": "Diversos",
        "estoque": 48,
        "descricao": "Kit completo de maquiagem para todos os tipos de pele",
        "especificacoes": "Paleta 12 cores, base, blush, rímel, batom",
        "avaliacao": 4.6,
        "num_avaliacoes": 445,
        "peso": 0.5,
        "dimensoes": "25x20x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500"
    },
    {
        "nome": "Sérum Facial Vitamina C",
        "categoria": "Beleza",
        "subcategoria": "Skincare",
        "preco": 129.90,
        "marca": "SkinCare+",
        "cor": "N/A",
        "material": "Sérum",
        "estoque": 87,
        "descricao": "Sérum facial anti-idade com vitamina C",
        "especificacoes": "30ml, dermatologicamente testado, todos os tipos de pele",
        "avaliacao": 4.7,
        "num_avaliacoes": 612,
        "peso": 0.1,
        "dimensoes": "10x4x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500"
    },
    {
        "nome": "Creme Hidratante Facial",
        "categoria": "Beleza",
        "subcategoria": "Skincare",
        "preco": 89.90,
        "marca": "SkinCare+",
        "cor": "N/A",
        "material": "Creme",
        "estoque": 112,
        "descricao": "Creme hidratante para rosto com ácido hialurônico",
        "especificacoes": "50ml, hidratação 24h, absorção rápida",
        "avaliacao": 4.6,
        "num_avaliacoes": 789,
        "peso": 0.12,
        "dimensoes": "8x8x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500"
    },
    {
        "nome": "Shampoo Hidratação Profunda",
        "categoria": "Beleza",
        "subcategoria": "Cabelos",
        "preco": 45.90,
        "marca": "HairPro",
        "cor": "N/A",
        "material": "Líquido",
        "estoque": 156,
        "descricao": "Shampoo para hidratação profunda dos fios",
        "especificacoes": "400ml, sem sal, óleo de argan, todos os tipos de cabelo",
        "avaliacao": 4.5,
        "num_avaliacoes": 923,
        "peso": 0.45,
        "dimensoes": "20x6x6cm",
        "imagem_url": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500"
    },
    {
        "nome": "Condicionador Reparação",
        "categoria": "Beleza",
        "subcategoria": "Cabelos",
        "preco": 45.90,
        "marca": "HairPro",
        "cor": "N/A",
        "material": "Creme",
        "estoque": 145,
        "descricao": "Condicionador para reparação de fios danificados",
        "especificacoes": "400ml, queratina, desembaraça, brilho intenso",
        "avaliacao": 4.5,
        "num_avaliacoes": 856,
        "peso": 0.45,
        "dimensoes": "20x6x6cm",
        "imagem_url": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500"
    },
    {
        "nome": "Esmalte Kit 10 Cores",
        "categoria": "Beleza",
        "subcategoria": "Unhas",
        "preco": 69.90,
        "marca": "NailArt",
        "cor": "Variado",
        "material": "Esmalte",
        "estoque": 95,
        "descricao": "Kit com 10 esmaltes de cores variadas",
        "especificacoes": "8ml cada, secagem rápida, longa duração",
        "avaliacao": 4.4,
        "num_avaliacoes": 534,
        "peso": 0.25,
        "dimensoes": "15x12x5cm",
        "imagem_url": "https://images.unsplash.com/photo-1610992015762-45b1f4e7b2b8?w=500"
    },
    {
        "nome": "Batom Matte Vermelho",
        "categoria": "Beleza",
        "subcategoria": "Maquiagem",
        "preco": 39.90,
        "marca": "BeautyPro",
        "cor": "Vermelho",
        "material": "Batom",
        "estoque": 178,
        "descricao": "Batom matte de longa duração",
        "especificacoes": "4g, acabamento matte, não transfere, hidratante",
        "avaliacao": 4.7,
        "num_avaliacoes": 1245,
        "peso": 0.05,
        "dimensoes": "8x2x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500"
    },
    {
        "nome": "Desodorante Antitranspirante",
        "categoria": "Beleza",
        "subcategoria": "Higiene",
        "preco": 19.90,
        "marca": "FreshCare",
        "cor": "N/A",
        "material": "Roll-on",
        "estoque": 245,
        "descricao": "Desodorante antitranspirante 48h",
        "especificacoes": "50ml, roll-on, sem álcool, dermatologicamente testado",
        "avaliacao": 4.3,
        "num_avaliacoes": 1567,
        "peso": 0.08,
        "dimensoes": "12x4x4cm",
        "imagem_url": "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?w=500"
    },

    # ========================================
    # MÓVEIS (5 produtos)
    # ========================================
    {
        "nome": "Cadeira Gamer Ergonômica",
        "categoria": "Móveis",
        "subcategoria": "Cadeiras",
        "preco": 899.90,
        "preco_promocional": 699.90,
        "marca": "GameSeats",
        "cor": "Preto/Vermelho",
        "material": "Couro sintético e espuma de alta densidade",
        "estoque": 15,
        "descricao": "Cadeira gamer com ajuste de altura, braços 4D e reclinável até 180°",
        "especificacoes": "Base metálica, rodas 360°, suporta até 150kg",
        "avaliacao": 4.7,
        "num_avaliacoes": 1034,
        "peso": 22.5,
        "dimensoes": "70x70x130cm",
        "imagem_url": "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=500"
    },
    {
        "nome": "Mesa Escritório L 120cm",
        "categoria": "Móveis",
        "subcategoria": "Mesas",
        "preco": 599.90,
        "marca": "OfficePro",
        "cor": "Branco/Madeira",
        "material": "MDF",
        "estoque": 22,
        "descricao": "Mesa em formato L para home office",
        "especificacoes": "120x120cm, gavetas, suporte para CPU",
        "avaliacao": 4.5,
        "num_avaliacoes": 267,
        "peso": 35.0,
        "dimensoes": "120x120x75cm",
        "imagem_url": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500"
    },
    {
        "nome": "Estante Livros 5 Prateleiras",
        "categoria": "Móveis",
        "subcategoria": "Estantes",
        "preco": 349.90,
        "preco_promocional": 279.90,
        "marca": "HomeFurniture",
        "cor": "Branco",
        "material": "MDP",
        "estoque": 38,
        "descricao": "Estante vertical com 5 prateleiras",
        "especificacoes": "60x180cm, acabamento fosco, suporta 15kg/prateleira",
        "avaliacao": 4.4,
        "num_avaliacoes": 312,
        "peso": 18.0,
        "dimensoes": "60x30x180cm",
        "imagem_url": "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=500"
    },
    {
        "nome": "Poltrona Decorativa Veludo",
        "categoria": "Móveis",
        "subcategoria": "Poltronas",
        "preco": 799.90,
        "marca": "ComfortHome",
        "cor": "Azul Petróleo",
        "material": "Veludo e madeira",
        "estoque": 18,
        "descricao": "Poltrona decorativa elegante em veludo",
        "especificacoes": "Pés palito, encosto alto, almofada inclusa",
        "avaliacao": 4.8,
        "num_avaliacoes": 189,
        "peso": 15.0,
        "dimensoes": "70x80x90cm",
        "imagem_url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500"
    },
    {
        "nome": "Rack TV até 55 Polegadas",
        "categoria": "Móveis",
        "subcategoria": "Racks",
        "preco": 449.90,
        "marca": "HomeFurniture",
        "cor": "Preto Fosco",
        "material": "MDP",
        "estoque": 32,
        "descricao": "Rack para TV com nichos e gavetas",
        "especificacoes": "150cm, 2 nichos, 2 gavetas, pés metálicos",
        "avaliacao": 4.6,
        "num_avaliacoes": 445,
        "peso": 25.0,
        "dimensoes": "150x40x60cm",
        "imagem_url": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500"
    },

    # ========================================
    # CASA & DECORAÇÃO (5 produtos)
    # ========================================
    {
        "nome": "Luminária LED de Mesa",
        "categoria": "Casa & Decoração",
        "subcategoria": "Luminárias",
        "preco": 89.90,
        "marca": "LightHome",
        "cor": "Branco",
        "material": "Plástico ABS",
        "estoque": 95,
        "descricao": "Luminária LED de mesa com 3 níveis de intensidade",
        "especificacoes": "Touch, USB recarregável, luz branca ajustável",
        "avaliacao": 4.5,
        "num_avaliacoes": 523,
        "peso": 0.4,
        "dimensoes": "35x12x12cm",
        "imagem_url": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500"
    },
    {
        "nome": "Quadro Decorativo Abstrato",
        "categoria": "Casa & Decoração",
        "subcategoria": "Quadros",
        "preco": 129.90,
        "marca": "ArtDecor",
        "cor": "Colorido",
        "material": "Canvas",
        "estoque": 67,
        "descricao": "Quadro decorativo com arte abstrata moderna",
        "especificacoes": "60x80cm, moldura inclusa, pronto para pendurar",
        "avaliacao": 4.6,
        "num_avaliacoes": 234,
        "peso": 1.2,
        "dimensoes": "60x80x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=500"
    },
    {
        "nome": "Tapete Sala Felpudo",
        "categoria": "Casa & Decoração",
        "subcategoria": "Tapetes",
        "preco": 199.90,
        "preco_promocional": 159.90,
        "marca": "HomeConfort",
        "cor": "Cinza",
        "material": "Poliéster",
        "estoque": 42,
        "descricao": "Tapete felpudo macio para sala",
        "especificacoes": "200x150cm, pelo alto, antiderrapante",
        "avaliacao": 4.7,
        "num_avaliacoes": 389,
        "peso": 3.5,
        "dimensoes": "200x150x3cm",
        "imagem_url": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=500"
    },
    {
        "nome": "Jogo Cama Casal 4 Peças",
        "categoria": "Casa & Decoração",
        "subcategoria": "Cama & Banho",
        "preco": 149.90,
        "marca": "SleepWell",
        "cor": "Branco",
        "material": "Algodão 200 fios",
        "estoque": 78,
        "descricao": "Jogo de cama casal premium 4 peças",
        "especificacoes": "1 lençol, 1 fronha, 2 fronhas, algodão egípcio",
        "avaliacao": 4.6,
        "num_avaliacoes": 567,
        "peso": 1.8,
        "dimensoes": "40x30x10cm",
        "imagem_url": "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500"
    },
    {
        "nome": "Kit Toalhas Banho 5 Peças",
        "categoria": "Casa & Decoração",
        "subcategoria": "Cama & Banho",
        "preco": 119.90,
        "marca": "BathPro",
        "cor": "Azul",
        "material": "Algodão 500g/m²",
        "estoque": 105,
        "descricao": "Kit com 5 toalhas de banho premium",
        "especificacoes": "2 banho, 2 rosto, 1 piso, alta absorção",
        "avaliacao": 4.5,
        "num_avaliacoes": 445,
        "peso": 2.5,
        "dimensoes": "35x25x15cm",
        "imagem_url": "https://images.unsplash.com/photo-1616627547584-bf28cfecc7e5?w=500"
    },

    # ========================================
    # LIVROS & PAPELARIA (5 produtos)
    # ========================================
    {
        "nome": "Caderno Universitário 200 Folhas",
        "categoria": "Papelaria",
        "subcategoria": "Cadernos",
        "preco": 29.90,
        "marca": "SchoolPro",
        "cor": "Variado",
        "material": "Papel",
        "estoque": 245,
        "descricao": "Caderno universitário 10 matérias",
        "especificacoes": "200 folhas, capa dura, espiral, pautado",
        "avaliacao": 4.4,
        "num_avaliacoes": 1234,
        "peso": 0.6,
        "dimensoes": "28x20x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=500"
    },
    {
        "nome": "Kit Canetas Coloridas 12 Cores",
        "categoria": "Papelaria",
        "subcategoria": "Canetas",
        "preco": 24.90,
        "marca": "WritePro",
        "cor": "Colorido",
        "material": "Plástico",
        "estoque": 312,
        "descricao": "Kit com 12 canetas coloridas",
        "especificacoes": "Ponta fina 0.7mm, tinta gel, cores vibrantes",
        "avaliacao": 4.5,
        "num_avaliacoes": 789,
        "peso": 0.15,
        "dimensoes": "18x12x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=500"
    },
    {
        "nome": "Planner 2025 Capa Dura",
        "categoria": "Papelaria",
        "subcategoria": "Planners",
        "preco": 69.90,
        "marca": "Organize+",
        "cor": "Rosa Gold",
        "material": "Papel",
        "estoque": 87,
        "descricao": "Planner 2025 para organização pessoal",
        "especificacoes": "365 dias, capa dura, marcador, bolso interno",
        "avaliacao": 4.7,
        "num_avaliacoes": 456,
        "peso": 0.5,
        "dimensoes": "21x15x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=500"
    },
    {
        "nome": "Estojo Escolar 3 Compartimentos",
        "categoria": "Papelaria",
        "subcategoria": "Estojos",
        "preco": 39.90,
        "marca": "SchoolPro",
        "cor": "Azul",
        "material": "Poliéster",
        "estoque": 156,
        "descricao": "Estojo escolar com 3 compartimentos",
        "especificacoes": "Zíperes resistentes, alça, espaçoso",
        "avaliacao": 4.4,
        "num_avaliacoes": 623,
        "peso": 0.2,
        "dimensoes": "22x10x8cm",
        "imagem_url": "https://images.unsplash.com/photo-1612534847738-b7d27bf39952?w=500"
    },
    {
        "nome": "Livro: Produtividade Máxima",
        "categoria": "Livros",
        "subcategoria": "Desenvolvimento Pessoal",
        "preco": 49.90,
        "marca": "Editora Prime",
        "cor": "N/A",
        "material": "Papel",
        "estoque": 125,
        "descricao": "Livro sobre produtividade e gestão de tempo",
        "especificacoes": "320 páginas, capa comum, best-seller",
        "avaliacao": 4.8,
        "num_avaliacoes": 1567,
        "peso": 0.4,
        "dimensoes": "23x16x2cm",
        "imagem_url": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500"
    }
]

# ========================================
# EXECUTAR POPULAÇÃO
# ========================================

print("🎯 POPULAÇÃO DE 100 PRODUTOS - CATÁLOGO COMPLETO\n")
print("=" * 80)

produtos_adicionados = 0
produtos_existentes = 0
produtos_com_imagem = 0
erros = 0

for i, dados in enumerate(produtos_teste, 1):
    try:
        existe = Produto.objects.filter(nome=dados['nome']).exists()
        
        if existe:
            print(f"[{i}/100] ⚠️  Já existe: {dados['nome']}")
            produtos_existentes += 1
        else:
            produto = Produto.objects.create(**dados)
            print(f"[{i}/100] ✅ {produto.nome[:50]}... | R$ {produto.preco} | {produto.estoque} un.")
            
            if produto.tem_imagem():
                produtos_com_imagem += 1
            
            produtos_adicionados += 1
            
    except Exception as e:
        print(f"[{i}/100] ❌ Erro: {dados['nome']} - {str(e)}")
        erros += 1

print("\n" + "=" * 80)
print(f"📊 RESUMO FINAL")
print("=" * 80)
print(f"   ✅ Produtos adicionados: {produtos_adicionados}")
print(f"   ⚠️  Já existiam: {produtos_existentes}")
print(f"   ❌ Erros: {erros}")
print(f"   📸 Com imagem: {produtos_com_imagem}")
print(f"   📦 Total no catálogo: {Produto.objects.count()}")

# Estatísticas detalhadas
print(f"\n🎯 ESTATÍSTICAS POR CATEGORIA:")
print("=" * 80)

from django.db.models import Count, Avg
categorias = Produto.objects.values('categoria').annotate(
    total=Count('id'),
    preco_medio=Avg('preco')
).order_by('-total')

for cat in categorias:
    print(f"   📦 {cat['categoria']:20} | {cat['total']:3} produtos | Preço médio: R$ {cat['preco_medio']:.2f}")

# Faixa de preço
print(f"\n💰 DISTRIBUIÇÃO POR PREÇO:")
print("=" * 80)
economicos = Produto.objects.filter(preco__lt=100).count()
intermediarios = Produto.objects.filter(preco__gte=100, preco__lt=300).count()
premium = Produto.objects.filter(preco__gte=300).count()

print(f"   💵 Econômicos (< R$ 100):     {economicos:3} produtos")
print(f"   💎 Intermediários (R$ 100-300): {intermediarios:3} produtos")
print(f"   👑 Premium (> R$ 300):         {premium:3} produtos")

# Promoções
print(f"\n🔥 PRODUTOS EM PROMOÇÃO:")
print("=" * 80)
em_promocao = Produto.objects.filter(preco_promocional__isnull=False).count()
print(f"   Total em promoção: {em_promocao} produtos")

# Estoque
print(f"\n📦 SITUAÇÃO DE ESTOQUE:")
print("=" * 80)
alto_estoque = Produto.objects.filter(estoque__gte=100).count()
medio_estoque = Produto.objects.filter(estoque__gte=50, estoque__lt=100).count()
baixo_estoque = Produto.objects.filter(estoque__gt=0, estoque__lt=50).count()
sem_estoque = Produto.objects.filter(estoque=0).count()

print(f"   🟢 Alto estoque (≥100):   {alto_estoque:3} produtos")
print(f"   🟡 Médio estoque (50-99): {medio_estoque:3} produtos")
print(f"   🟠 Baixo estoque (1-49):  {baixo_estoque:3} produtos")
print(f"   🔴 Sem estoque:           {sem_estoque:3} produtos")

# Avaliações
print(f"\n⭐ AVALIAÇÕES:")
print("=" * 80)
excelentes = Produto.objects.filter(avaliacao__gte=4.7).count()
boas = Produto.objects.filter(avaliacao__gte=4.0, avaliacao__lt=4.7).count()
regulares = Produto.objects.filter(avaliacao__lt=4.0).count()

print(f"   ⭐⭐⭐⭐⭐ Excelentes (≥4.7): {excelentes:3} produtos")
print(f"   ⭐⭐⭐⭐   Boas (4.0-4.6):    {boas:3} produtos")
print(f"   ⭐⭐⭐     Regulares (<4.0):  {regulares:3} produtos")

print("\n" + "=" * 80)
print(f"⚡ PRÓXIMOS PASSOS:")
print("=" * 80)
print(f"   1. cd {project_root}")
print(f"   2. python manage.py popular_embeddings --force")
print(f"   3. python manage.py runserver")
print(f"   4. Testar: http://localhost:8000/api/rag/query/")
print("=" * 80)
print("\n🎉 CATÁLOGO COMPLETO POPULADO COM SUCESSO!\n")