# Generated by Django 5.2.8 on 2025-11-16 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('descricao', models.TextField(blank=True, null=True)),
                ('especificacoes', models.TextField(blank=True, null=True)),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('num_avaliacoes', models.IntegerField(default=0)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, help_text='Peso em quilogramas', max_digits=8, null=True)),
                ('dimensoes', models.CharField(blank=True, help_text='Formato: LxAxP cm', max_length=50, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'ordering': ['-data_cadastro'],
                'indexes': [models.Index(fields=['nome'], name='produtos_nome_8fe6f1_idx'), models.Index(fields=['categoria'], name='produtos_categor_336244_idx'), models.Index(fields=['preco'], name='produtos_preco_7f62fb_idx')],
            },
        ),
    ]
