# Generated by Django 5.2.9 on 2025-12-03 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('temporario', 'Temporário'), ('atualizavel', 'Atualizável'), ('estatico', 'Estático')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('prioridade', models.IntegerField(default=0)),
                ('cor', models.CharField(default='#3B82F6', max_length=7)),
                ('icone', models.CharField(default='📚', max_length=50)),
                ('auto_expiracao', models.BooleanField(default=False)),
                ('dias_expiracao', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base de Conhecimento',
                'verbose_name_plural': 'Bases de Conhecimento',
                'ordering': ['-prioridade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('arquivado', 'Arquivado'), ('expirado', 'Expirado')], default='ativo', max_length=20)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('versao', models.IntegerField(default=1)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_gerado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes', to='meu_app_rag.documento')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='meu_app_rag.knowledgebase')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='meu_app_rag_status_684920_idx'), models.Index(fields=['base', 'status'], name='meu_app_rag_base_id_1a603e_idx'), models.Index(fields=['data_fim'], name='meu_app_rag_data_fi_cb86c4_idx')],
                'unique_together': {('base', 'slug')},
            },
        ),
    ]
