# Generated by Django 5.2.8 on 2025-11-20 18:12

import django.core.validators
import meu_app_rag.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app_rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do produto (JPG, PNG, WebP) - Máx: 5MB', null=True, upload_to='produtos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), meu_app_rag.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Miniatura gerada automaticamente (200x200)', null=True, upload_to='produtos/%Y/%m/thumbnails/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='URL da imagem (alternativa ao upload)', max_length=500, null=True),
        ),
    ]
